pool:
    vmImage: "ubuntu-16.04"
strategy:
    matrix:
        node_8_x:
            node_version: 8.x
        node_9_x:
            node_version: 9.x
# Archive Files
# Archive files using compression formats such as .7z, .rar, .tar.gz, and .zip.
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)' 
    includeRootFolder: true
    archiveType: 'zip' # Options: zip, 7z, tar, wim
    tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
    replaceExistingArchive: true 
steps:
    - task: NodeTool@0
      inputs:
          versionSpec: $(node_version)

    - script: npm install && npm run build
